package jenkinsfiles

def NAME = 'todo-app'
def PROJECT = 'main'
def GIT_URL = 'https://github.com/steven166/todo-app.git'
def ROUTES = "/api/v1/todos";
def POSTMAN_COLLECTION = "/build/reports/collection.json";

node('maven') {

    stage('Checkout') {
        git GIT_URL
    }

    stage('Prepare Build') {
        // Setup image stream
        try {
            sh "oc process -f src/pipeline/templates/imagestream-app.template.yml -v NAME=${NAME} | oc replace -f -"
        } catch (Exception e) {
            sh "oc process -f src/pipeline/templates/imagestream-app.template.yml -v NAME=${NAME} | oc replace --force -f -"
        }
        // Setup docker build config
        try {
            sh "oc process -f src/pipeline/templates/build-docker.template.yml -v NAME=${NAME} -v TAG=snapshot | oc replace -f -"
        } catch (Exception e) {
            sh "oc process -f src/pipeline/templates/build-docker.template.yml -v NAME=${NAME} -v TAG=snapshot | oc replace --force -f -"
        }
    }

    stage('Build') {
        sh 'chmod 777 ./gradlew'
        sh './gradlew build -x test'
    }

    stage('Build Docker Image') {

        parallel 'Build Docker Image': {
            sh "oc start-build ${NAME}-snapshot --from-dir=. -F -w"

        }, 'Test and Report': {
            sh './gradlew test buildJavaDoc microdocs'
            stash includes: 'build/reports/**', name: 'reports'
        }
    }

    stage('Publish develop') {

        parallel 'Promote Image': {
            sh "oc tag ${PROJECT}/${NAME}:snapshot ${PROJECT}/${NAME}:dev"

        }, 'Publish reports': {
            unstash 'reports'
            // Publish JUnit reports
            junit allowEmptyResults: true, testResults: 'build/test-results/*.xml'
            // Publish JavaDoc
            archive 'build/reports/**'
            // mdocs publish -d build/reports/microdocs.json
        }
    }

    stage('Prepare Deployment') {
        try {
            sh "oc process -f src/pipeline/templates/dc_app.template.yml -v NAME=${NAME} -v IMAGE=${NAME} -v TAG=dev | oc replace -f -"
        } catch (Exception e) {
            sh "oc new-app ${NAME}"
            sh "oc process -f src/pipeline/templates/dc_app.template.yml -v NAME=${NAME} -v IMAGE=${NAME} -v TAG=dev | oc replace -f -"
        }
    }

    stage('Deploy develop') {
        sh "oc rollout latest dc/${NAME}"
    }

    stage('Expose routes') {
        def routes = ROUTES.split(',');
        for (int index = 0; index < routes.length; index++) {
            def route = routes[index];
            def routeName = NAME + '-' + index;
            try {
                sh "oc process -f src/pipeline/templates/dc_route.template.yml -v NAME=${routeName} -v SERVICE=${NAME} -v PATH=${route} | oc replace -f -"
            } catch (Exception e) {
                sh "oc process -f src/pipeline/templates/dc_route.template.yml -v NAME=${routeName} -v SERVICE=${NAME} -v PATH=${route} | oc replace --force -f -"
            }
        }
    }

    if(fileExists(POSTMAN_COLLECTION)) {
        stage('Prepare Api Test') {
            try {
                sh "oc process -f src/pipeline/templates/dc_app.template.yml -v NAME=${NAME}-test -v IMAGE=${NAME} -v TAG=dev | oc replace -f -"
            } catch (Exception e) {
                sh "oc new-app ${NAME}"
                sh "oc process -f src/pipeline/templates/dc_app.template.yml -v NAME=${NAME}-test -v IMAGE=${NAME} -v TAG=dev | oc replace -f -"
            }

            stash includes: POSTMAN_COLLECTION, name: 'api-test'
        }
    }
}

if(fileExists(POSTMAN_COLLECTION)) {
    node('nodejs') {
        stage('Install newman') {
            sh 'npm install -g newman'
        }
        stage('Run Api Test') {
            unstash name: 'api-test'
            sh "newman -c ${POSTMAN_COLLECTION} --exitCode 1"
        }
    }
}