def NAME = 'todo-app'
def PROJECT = 'main'
def GIT_URL = 'https://github.com/steven166/todo-app.git'
def ROUTES = ["/api/v1"];

node('maven') {
    stage('Checkout') {
        git GIT_URL
    }
    stage('Build') {
        sh 'chmod 777 ./gradlew'
        sh './gradlew build -x test'
    }
    stage('Build parallel') {
        parallel 'Build Docker Image': {
//            echo 'Update Docker build-config'
//            try {
//                // Delete old Build Config
//                sh "oc delete bc/${NAME}-snapshot"
//            } catch (Exception e) {
//            }
            try {
                sh "oc process -f src/pipeline/bc_docker.template.yml -v NAME=${NAME} -v TAG=snapshot | oc replace -f -"
            } catch (Exception e) {
                sh "oc process -f src/pipeline/bc_docker.template.yml -v NAME=${NAME} -v TAG=snapshot | oc replace --force -f -"
            }
            echo 'Build Docker Image'
            sh "oc start-build ${NAME}-snapshot --from-dir=. -F -w"
        }, 'Test and Report': {
            sh './gradlew test buildJavaDoc microdocs'
            stash includes: 'build/reports/**', name: 'reports'
        }
    }
    stage('Publish develop') {
        parallel 'Promote Image': {
            sh "oc tag ${PROJECT}/${NAME}:snapshot ${PROJECT}/${NAME}:dev"
        }, 'Publish reports': {
            unstash 'reports'
            // Publish JUnit reports
            junit allowEmptyResults: true, testResults: 'build/test-results/*.xml'
            // Publish JavaDoc
            archive 'build/reports/**'
            // mdocs publish -d build/reports/microdocs.json
        }
    }
    stage('Prepair Deployment') {
        try {
            sh "oc process -f src/pipeline/dc_app.template.yml -v NAME=${NAME} -v TAG=dev | oc replace -f -"
        } catch (Exception e) {
            sh "oc new-app ${NAME}"
            sh "oc process -f src/pipeline/dc_app.template.yml -v NAME=${NAME} -v TAG=dev | oc replace -f -"
        }
    }
    stage('Deploy develop') {
        sh "oc rollout latest dc/${NAME}"
    }
    stage('Expose routes') {
        for(int index = 0; index < ROUTES.size(); i++)
            def route = ROUTES.get(index);
            def routeName = NAME + '_' + index;
            try {
                sh "oc process -f src/pipeline/dc_route.template.yml -v NAME=${routeName} -v SERVICE=${NAME} -v PATH=${route} | oc replace -f -"
            } catch (Exception e) {
                sh "oc process -f src/pipeline/dc_route.template.yml -v NAME=${routeName} -v SERVICE=${NAME} -v PATH=${route} | oc replace --force -f -"
            }
        }
    }
}