# JRE based on centos7
FROM openshift/base-centos7
MAINTAINER Steven Hermans <s.hermans@maxxton.com>
# HOME in base image is /opt/app-root/src

# Install build tools on top of base image
# Java jdk 8, Maven 3.3, Gradle 2.6
#RUN INSTALL_PKGS="tar unzip bc which lsof java-1.8.0-openjdk java-1.8.0-openjdk-devel" && \
#    yum install -y --enablerepo=centosplus $INSTALL_PKGS && \
#    rpm -V $INSTALL_PKGS && \
#    yum clean all -y && \
#    mkdir -p /opt/openshift && \
#    mkdir -p /opt/app-root/source && chmod -R a+rwX /opt/app-root/source && \
#    mkdir -p /opt/s2i/destination && chmod -R a+rwX /opt/s2i/destination && \
#    mkdir -p /opt/app-root/src && chmod -R a+rwX /opt/app-root/src

# Install Oracle Java 8 JRE
RUN cd ~ && \
    wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jre-8u60-linux-x64.rpm" && \
    yum localinstall -y jre-8u60-linux-x64.rpm && \
    rm ~/jre-8u60-linux-x64.rpm


LABEL io.k8s.description="Running Jars using the JRE" \
      io.k8s.display-name="Java JRE Openshift" \
      io.openshift.expose-services="8080:http" \
      io.openshift.tags="java,microservices,fatjar"

WORKDIR /opt/openshift

RUN chown -R 1001:1001 /opt/openshift

# This default user is created in the openshift/base-centos7 image
USER 1001

# Set the default port for applications built using this image
EXPOSE 8080

# Set the default CMD for the image
CMD ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/opt/openshift/app.jar"]